// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import type { SupabaseClient } from '@supabase/supabase-js';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: SupabaseClient<Database> = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Typed helpers for dynamic access when the exact table or RPC
// name is not known at compile time. Prefer using `supabase` with
// concrete table names from `Database` when possible.
export function fromAny<T extends keyof Database['public']['Tables']>(table: T) {
  return (supabase as any).from(table) as any;
}

export function rpcAny<TResult = unknown>(fn: string, params?: any) {
  return (supabase.rpc as any)(fn, params) as ReturnType<typeof supabase.rpc> & { data: TResult };
}