// Temporary minimal Supabase types shim.
// This is a lightweight placeholder to keep TypeScript happy until
// the real types are generated by the Supabase CLI and committed.

export type Json =
	| string
	| number
	| boolean
	| null
	| { [key: string]: Json }
	| Json[];

export interface Database {
	public: {
		Tables: {
			[table: string]: {
				Row: Record<string, any>;
				Insert: Record<string, any>;
				Update: Record<string, any>;
			};
		};
		Views: {
			[view: string]: {
				Row: Record<string, any>;
			};
		};
		Functions: {
			[fn: string]: {
				Args: Record<string, any> | undefined;
				Returns: any;
			};
		};
		Enums: Record<string, never>;
		CompositeTypes: Record<string, never>;
	};
}

export type JsonValue = Json;

export type SupabaseTypes = Database;

// NOTE: Replace this file with the autogenerated `types.ts` from
// `npx supabase gen types typescript` once the workflow runs successfully.

